#' Verify Aligned Fragments
#'
#' Verifies that aligned fragments are contained within the ground-truth fragments generated by <code>make_fragments()</code>.
#' Aligned fragments that are not contained within the generated fragments are discarded.
#' Properly aligned fragments are returned.
#'
#'@param generated.fragments The fragments generated by <code>make_fragments()</code>.
#'@param aligned.fragments The fragments mapped in the alignment.
#'
#'@return A GRanges object containing the verified aligned fragments.
#'
#'@import GenomicRanges
#'
#'@export
#'
verify_aligned_fragments <- function( generated.fragments,
                                      aligned.fragments ){

  if( is.unsorted( generated.fragments ) ){
    generated.fragments <- sort( generated.fragments, ignore.strand = TRUE )
  }

  if( is.unsorted( aligned.fragments ) ){
    aligned.fragments <- sort( aligned.fragments, ignore.strand = TRUE )
  }

  comparison <- match( x = aligned.fragments, table = generated.fragments )

  matched <- aligned.fragments[ !is.na( comparison ) ]

  return( matched )

}
